<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
		<Platforms>x64</Platforms>
	</PropertyGroup>
	
	<PropertyGroup>
		<EnableDefaultItems>false</EnableDefaultItems>
		<AssemblyName>FAudio-CS</AssemblyName>
		<RootNamespace>FAudio</RootNamespace>
	</PropertyGroup>

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
        <Configurations>DebugLinuxArm32;DebugLinuxX64;DebugWindowsX64;DebugWindowsAOTX64</Configurations>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
        <Nullable>enable</Nullable>
        <OutputPath>bin\$(Configuration)</OutputPath>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <Platforms>AnyCPU</Platforms>
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <Optimize>true</Optimize>
        <WarningLevel>5</WarningLevel>
    </PropertyGroup>
	
    <ItemGroup>
		<Compile Include="FAudio.cs" />
	</ItemGroup>
	<ItemGroup>
		<None Include="app.config" />
	</ItemGroup>
</Project>
