<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
		<Platforms>x64</Platforms>
	</PropertyGroup>
	
	<PropertyGroup>
		<EnableDefaultItems>false</EnableDefaultItems>
		<AssemblyName>FAudio-CS</AssemblyName>
		<RootNamespace>FAudio</RootNamespace>
	</PropertyGroup>
	
	<PropertyGroup>
        <SelfContained>true</SelfContained>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    </PropertyGroup>

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
        <Configurations>DebugLinuxArm32;DebugLinuxX64;DebugWindowsX64;DebugWindowsAOTX64</Configurations>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
        <Nullable>enable</Nullable>
        <OutputPath>bin\$(Configuration)</OutputPath>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <Platforms>AnyCPU</Platforms>
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <Optimize>true</Optimize>
        <WarningLevel>5</WarningLevel>
    </PropertyGroup>
	
	
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugWindowsX64|AnyCPU'">
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <Optimize>False</Optimize>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugWindowsAOTX64|AnyCPU'">
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
        <DefineConstants>TRACE;DEBUG;WindowsX64;NATIVEAOT</DefineConstants>
        <Optimize>false</Optimize>
        <PublishAot>true</PublishAot>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)|$(Platform)'=='DebugWindowsAOTX64|AnyCPU'">
        <RuntimeHostConfigurationOption Include="System.Runtime.InteropServices.EnableCppInterop" Value="true" />
    </ItemGroup>


	
    <ItemGroup>
		<Compile Include="FAudio.cs" />
	</ItemGroup>
	<ItemGroup>
		<None Include="app.config" />
	</ItemGroup>
</Project>
